#!/bin/sh
#
# Plugin to monitor Bacula job
#
#


if [ "$1" = "autoconf" ]; then
    # Makes little sense to autoconf if you can't suggest
    echo no
    exit 0
fi

if [ "$1" = "suggest" ]; then
	exit 0
fi

nclients=( $(echo "memory"|/opt/bacula/bin/bconsole|grep " Res: " | awk '{split($3,field,"=");} { print field[2]; }' ))
njobs=( $(echo "memory"|/opt/bacula/bin/bconsole|grep " Res: " | awk '{split($2,field,"=");} { print field[2]; }' ))
nstores=( $(echo "memory"|/opt/bacula/bin/bconsole|grep " Res: " | awk '{split($4,field,"=");} { print field[2]; }' ))
npools=( $(echo "memory"|/opt/bacula/bin/bconsole|grep " Res: " | awk '{split($5,field,"=");} { print field[2]; }' ))

if [ "$1" = "config" ]; then

	echo <<EOF "graph_title Bacula res
graph_args --base 1024 -r -l 0 --vertical-label Res 
graph_info Res
graph_category Bacula
graph_period second

nclients.label Clients
nclients.draw LINE1
nclients.info Clients
nclients.colour FF0000

njobs.label Jobs
njobs.draw LINE1
njobs.info Jobs
njobs.colour 0066cc

nstores.label Stores
nstores.draw LINE1
nstores.info Stores
nstores.colour fbb087

npools.label Pools
npools.draw LINE1
npools.info Pools
npools.colour e52e90
"
EOF
	exit 0
fi

echo "nclients.value ${nclients[0]}"
echo "njobs.value ${njobs[0]}"
echo "nstores.value ${nstores[0]}"
echo "npools.value ${npools[0]}"

exit 0

