#!/bin/sh
#
# Plugin to monitor Bacula job
#
#


if [ "$1" = "autoconf" ]; then
    # Makes little sense to autoconf if you can't suggest
    echo no
    exit 0
fi

if [ "$1" = "suggest" ]; then
	exit 0
fi

medias=( $( echo "sql
select count(*) from media;" | /opt/bacula/bin/bconsole | awk 'NR==14 {sub(",","",$2); print $2;}') )

if [ "$1" = "config" ]; then

	echo <<EOF "graph_title  Medias
graph_args --base 1024 -r -l 0 --vertical-label Medias 
graph_info Medias.
graph_category Bacula
graph_period second
medias.label Medias
medias.draw LINE1
medias.info Medias
medias.colour FF0000
"
EOF
	exit 0
fi

echo "medias.value ${medias[0]}"

exit 0

