#!/bin/sh
#
# Plugin to monitor Bacula job
#
#


if [ "$1" = "autoconf" ]; then
    # Makes little sense to autoconf if you can't suggest
    echo no
    exit 0
fi

if [ "$1" = "suggest" ]; then
	exit 0
fi

running=( $( echo "status dir"|/opt/bacula/bin/bconsole|grep " Jobs: run=" | cut -f4 -d' ' | awk 'match($0, /[0-9]+/) { print substr( $0, RSTART, RLENGTH )}') )

if [ "$1" = "config" ]; then

	echo <<EOF "graph_title running jobs 
graph_args --base 1024 -r -l 0 --vertical-label Jobs 
graph_info Running jobs.
graph_category Bacula
graph_period second
running.label Jobs
running.draw LINE1
running.info Arc Size
running.colour FF0000
"
EOF
	exit 0
fi

echo "running.value ${running[0]}"

exit 0

